# Generated by Django 4.0.4 on 2022-04-29 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_valoracio_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoracio',
            name='descripcio',
        ),
        migrations.AddField(
            model_name='valoracio',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
