# Generated by Django 4.0.4 on 2022-04-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_valoracio_descripcio_valoracio_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracio',
            name='valor',
            field=models.IntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2)], default=0),
        ),
    ]
