# Generated by Django 4.0.4 on 2022-04-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_valoracio_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracio',
            name='valor',
            field=models.IntegerField(choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=0),
        ),
    ]
