# Generated by Django 4.0.4 on 2022-04-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_valoracio_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='valoracio_mitja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
